#!/bin/bash
import curses

def draw_square(window, color):
    height, width = window.getmaxyx()
    for y in range(height):
        for x in range(width):
            window.addch(y, x, ' ', curses.color_pair(color))

def draw_question(window, question, selected_option):
    window.clear()
    draw_square(window, curses.COLOR_BLUE)  # Blue square

    window.addstr(2, 2, question, curses.A_BOLD)

    options = ["Yes", "No"]
    for i, option in enumerate(options):
        color = curses.color_pair(curses.COLOR_WHITE)
        if i == selected_option:
            color = curses.color_pair(curses.COLOR_BLUE) | curses.A_BOLD
        window.addstr(4 + i, 4, f"{option}", color)

    window.refresh()

def main(stdscr):
    curses.curs_set(0)  # Hide the cursor
    curses.start_color()
    curses.init_pair(curses.COLOR_BLUE, curses.COLOR_BLUE, curses.COLOR_BLACK)
    curses.init_pair(curses.COLOR_WHITE, curses.COLOR_WHITE, curses.COLOR_BLACK)

    question = "Do you like cookies?"
    selected_option = 0  # Default selection

    while True:
        draw_question(stdscr, question, selected_option)

        key = stdscr.getch()

        if key == curses.KEY_UP and selected_option > 0:
            selected_option -= 1
        elif key == curses.KEY_DOWN and selected_option < 1:
            selected_option += 1
        elif key == 10:  # Enter key
            break  # Exit the loop on Enter

curses.wrapper(main)